version: '3'

services:
  postgres:
    build: ./database/
    environment: 
      POSTGRES_PASSWORD: connorhoman
      POSTGRES_DB: listinginfo
      POSTGRES_USER: connorhoman

  listing:
    build: .
    ports: 
      - '3006:3006'
    depends_on:
      - 'postgres'
          
