version: '2'

networks: 
  listinginfo:
    external: true

services:
  postgres:
    build: ./database/
    environment: 
      POSTGRES_PASSWORD: connorhoman
      POSTGRES_DB: listinginfo
      POSTGRES_USER: connorhoman
    network_mode: 'host'

  listing:
    build: .
    environment: 
      - 'DB_HOST= postgres'
      - 'DB_PORT= 5432'
      - 'DB_DATABASE= listing_info'
    ports: 
      - '3006:3006'
    depends_on:
      - 'postgres'
    network_mode: 'host'
          
