version: '3'

networks: 
  mynet:
    external: true

services:
  postgres:
    build: ./database/
    environment: 
      POSTGRES_PASSWORD: connorhoman
      POSTGRES_DB: listinginfo
      POSTGRES_USER: connorhoman
    networks:
      - mynet
      - default

  listing:
    build: .
    ports: 
      - '3006:3006'
    depends_on:
      - 'postgres'
    networks:
      - mynet
      - default
          
