version: '3'

networks: 
  listinginfo:
    external: true

services:
  postgres:
    build: ./database/
    environment: 
      POSTGRES_PASSWORD: connorhoman
      POSTGRES_DB: listinginfo
      POSTGRES_USER: connorhoman
    networks:
      listinginfo:

  listing:
    build: .
    links: 
      - 'postgres'
    environment: 
      - 'DB_HOST= postgres'
      - 'DB_PORT= 5432'
      - 'DB_DATABASE= listinginfo'
    ports: 
      - '3006:3006'
    depends_on: 
      - 'postgres'
    networks:
      listinginfo:
          
