version: '2'

networks: 
  listinginfo:
    external: true

services:
  postgres:
    build: ./database/
    environment: 
      POSTGRES_PASSWORD: connorhoman
      POSTGRES_DB: listinginfo
      POSTGRES_USER: connorhoman
    networks:

        alias: postgres

  listing:
    build: .
    environment: 
      - 'DB_HOST= postgres'
      - 'DB_PORT= 5432'
      - 'DB_DATABASE= listing_info'
    ports: 
      - '3006:3006'
    networks:
      alias: server

  networks:
      driver: bridge
      driver_opts:
        com.docker.network.enable_ipv6: "true"
        com.docker.network.bridge.enable_ip_masquerade: "true"
      ipam:
        driver: default
        config:
        - subnet: 172.16.100.0/24
        - gateway: 172.16.100.1
          
